import { definePreset } from '@primeng/themes';
import Lara from '@primeng/themes/lara';

const LaraDark = definePreset(Lara, {
  semantic: {
    primary: {
      50: '{gray.50}',
      100: '{gray.100}',
      200: '{gray.200}',
      300: '{gray.300}',
      400: '{gray.400}',
      500: '{gray.500}',
      600: '{gray.600}',
      700: '{gray.700}',
      800: '{gray.800}',
      900: '{gray.900}',
      950: '{gray.950}',
    },
    colorScheme: {
      light: {
        surface: {
          0: '#ffffff',
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
          950: '#030712',
        },
        primary: {
          color: '{blue.500}',
          inverseColor: '#ffffff',
          hover: '{blue.400}',
          activeColor: '{blue.600}',
          borderColor: '{blue.200}',
        },
        highlight: {
          background: '{blue.50}',
          focusBackground: '{blue.100}',
          color: '{blue.700}',
          focusColor: '{blue.800}',
        },
        mask: {
          background: 'rgba(0, 0, 0, 0.4)',
          color: '{surface.0}',
        },
        formField: {
          background: '{surface.0}',
          disabledBackground: '{surface.200}',
          filledBackground: '{surface.50}',
          filledFocusBackground: '{surface.50}',
          borderColor: '{surface.300}',
          hoverBorderColor: '{surface.400}',
          focusBorderColor: '{primary.color}',
          invalidBorderColor: '{red.500}',
          color: '{surface.900}',
          disabledColor: '{surface.500}',
          placeholderColor: '{surface.500}',
          floatLabelBackground: '{surface.0}',
          floatLabelFocusBackground: '{surface.0}',
          floatLabelActiveColor: '{primary.color}',
          floatLabelInvalidColor: '{form.invalid.color}',
          iconColor: '{surface.400}',
        },
      },
      dark: {
        surface: {
          0: '#ffffff',
          50: '#f9fafb',
          100: '#f3f4f6',
          200: '#e5e7eb',
          300: '#d1d5db',
          400: '#9ca3af',
          500: '#6b7280',
          600: '#4b5563',
          700: '#374151',
          800: '#1f2937',
          900: '#111827',
          950: '#030712',
        },
        primary: {
          color: '{gray.300}',
          inverseColor: '{surface.950}',
          hover: '{gray.400}',
          activeColor: '{gray.200}',
          borderColor: '{gray.700}',
        },
        highlight: {
          background: 'rgba({gray.300}, 0.15)',
          focusBackground: 'rgba({gray.300}, 0.3)',
          color: '{gray.300}',
          focusColor: '{gray.400}',
        },
        mask: {
          background: 'rgba(0, 0, 0, 0.6)',
          color: '{surface.0}',
        },
        formField: {
          background: '{surface.800}',
          disabledBackground: '{surface.700}',
          filledBackground: '{surface.700}',
          filledFocusBackground: '{surface.700}',
          borderColor: '{surface.700}',
          hoverBorderColor: '{surface.600}',
          focusBorderColor: '{primary.color}',
          invalidBorderColor: '{red.400}',
          color: '{surface.0}',
          disabledColor: '{surface.400}',
          placeholderColor: '{surface.500}',
          floatLabelBackground: '{surface.800}',
          floatLabelFocusBackground: '{surface.800}',
          floatLabelActiveColor: '{primary.color}',
          floatLabelInvalidColor: '{form.invalid.color}',
          iconColor: '{surface.500}',
        },
      },
    },
  },
});

export default LaraDark;
